export const AUDIT_CATEGORIES = {
  AUTH: "AUTH",
  ACCOUNT: "ACCOUNT",
  PROFILE: "PROFILE",
  SECURITY: "SECURITY",
  SESSION: "SESSION",
  SEARCH: "SEARCH",
  PRODUCT: "PRODUCT",
  REVIEW: "REVIEW",
  COMMENT: "COMMENT",
  SOCIAL: "SOCIAL",
  ADMIN: "ADMIN",
  CONTENT: "CONTENT",
  PERMISSION: "PERMISSION",
  SYSTEM: "SYSTEM",
} as const;

export const AUDIT_ACTIONS = {
  // Authentication
  ACCOUNT_REGISTERED: "ACCOUNT_REGISTERED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",

  // Account
  ACCOUNT_DELETED: "ACCOUNT_DELETED",
  ACCOUNT_DISABLED: "ACCOUNT_DISABLED",
  ACCOUNT_ENABLED: "ACCOUNT_ENABLED",

  // Profile
  PROFILE_UPDATED: "PROFILE_UPDATED",
  PROFILE_IMAGE_UPLOADED: "PROFILE_IMAGE_UPLOADED",
  PROFILE_IMAGE_DELETED: "PROFILE_IMAGE_DELETED",

  // Security
  PASSWORD_CHANGED: "PASSWORD_CHANGED",
  PASSWORD_RESET_REQUESTED: "PASSWORD_RESET_REQUESTED",
  PASSWORD_RESET_COMPLETED: "PASSWORD_RESET_COMPLETED",

  // Session
  SESSION_CREATED: "SESSION_CREATED",
  SESSION_ENDED: "SESSION_ENDED",

  // Search
  SEARCH_PERFORMED: "SEARCH_PERFORMED",

  // Product
  PRODUCT_VIEWED: "PRODUCT_VIEWED",
  PRODUCT_CREATED: "PRODUCT_CREATED",
  PRODUCT_UPDATED: "PRODUCT_UPDATED",
  PRODUCT_DELETED: "PRODUCT_DELETED",

  // Reviews/comments
  REVIEW_CREATED: "REVIEW_CREATED",
  REVIEW_UPDATED: "REVIEW_UPDATED",
  REVIEW_DELETED: "REVIEW_DELETED",

  // Social
  PRODUCT_SHARED: "PRODUCT_SHARED",
  PRODUCT_FAVORITED: "PRODUCT_FAVORITED",
  PRODUCT_UNFAVORITED: "PRODUCT_UNFAVORITED",

  // Administration
  USER_VIEWED: "USER_VIEWED",
  USER_UPDATED: "USER_UPDATED",
  ADMIN_CREATED: "ADMIN_CREATED",
  ADMIN_UPDATED: "ADMIN_UPDATED",
  ADMIN_DISABLED: "ADMIN_DISABLED",
  ADMIN_ENABLED: "ADMIN_ENABLED",
  PERMISSION_GRANTED: "PERMISSION_GRANTED",
  PERMISSION_REVOKED: "PERMISSION_REVOKED",

  // Audit
  AUDIT_HISTORY_VIEWED: "AUDIT_HISTORY_VIEWED",
} as const;